using './main.bicep'

// Generated by citadel-image-models-tests.ipynb @ 2026-06-22 23:59:31
// Existing backends (from azd) + dedicated azure-flux / azure-mai image backends.

param apim = {
  subscriptionId: 'd2e7f84f-2790-4baa-9520-59ae8169ed0d'
  resourceGroupName: 'rg-ai-hub-citadel-dev-96'
  name: 'apim-rmwzy2zdoizg2'
}

param apimManagedIdentity = {
  subscriptionId: 'd2e7f84f-2790-4baa-9520-59ae8169ed0d'
  resourceGroupName: 'rg-ai-hub-citadel-dev-96'
  name: 'id-apim-rmwzy2zdoizg2'
}

param llmBackendConfig = [
  {
    backendId: 'aif-rmwzy2zdoizg2-0'
    backendType: 'ai-foundry'
    endpoint: 'https://aif-rmwzy2zdoizg2-0.cognitiveservices.azure.com/'
    authType: 'managed-identity'
    supportedModels: [
      { name: 'gpt-4.1', sku: 'GlobalStandard', modelFormat: 'OpenAI', modelVersion: '2025-04-14', retirementDate: '2026-10-14', apiVersion: '2025-04-01-preview', capacity: 100, timeout: 180 }
      { name: 'gpt-image-1.5', sku: 'GlobalStandard', modelFormat: 'OpenAI', modelVersion: '2025-12-16', retirementDate: '2026-12-16', inferenceApiVersion: '2024-05-01-preview', capacity: 2 }
      { name: 'MAI-Image-2.5-Flash', sku: 'GlobalStandard', modelFormat: 'Microsoft', modelVersion: '2026-06-02', retirementDate: '2026-09-01', inferenceApiVersion: '2024-05-01-preview', capacity: 1 }
      { name: 'FLUX.2-pro', sku: 'GlobalStandard', modelFormat: 'Black Forest Labs', modelVersion: '1', retirementDate: '2099-09-01', inferenceApiVersion: '2024-05-01-preview', capacity: 1 }
      { name: 'text-embedding-3-large', sku: 'GlobalStandard', modelFormat: 'OpenAI', modelVersion: '1', retirementDate: '2027-04-14', capacity: 100 }
      { name: 'Mistral-Large-3', sku: 'GlobalStandard', modelFormat: 'Mistral AI', modelVersion: '1', retirementDate: '2099-12-30', capacity: 100 }
      { name: 'gpt-5.4-mini', sku: 'GlobalStandard', modelFormat: 'OpenAI', modelVersion: '2026-03-17', retirementDate: '2026-09-30', capacity: 100 }
      { name: 'Phi-4', sku: 'GlobalStandard', modelFormat: 'Microsoft', modelVersion: '7', retirementDate: '2099-10-14', apiVersion: '2025-04-01-preview', capacity: 1, timeout: 180 }
    ]
    priority: 1
    weight: 100
  }
  {
    backendId: 'aif-rmwzy2zdoizg2-1'
    backendType: 'ai-foundry'
    endpoint: 'https://aif-rmwzy2zdoizg2-1.cognitiveservices.azure.com/'
    authType: 'managed-identity'
    supportedModels: [
      { name: 'Phi-4', sku: 'GlobalStandard', modelFormat: 'Microsoft', modelVersion: '7', retirementDate: '2099-10-14', apiVersion: '2025-04-01-preview', capacity: 1, timeout: 180 }
      { name: 'gpt-5.4-mini', sku: 'GlobalStandard', modelFormat: 'OpenAI', modelVersion: '2026-03-17', retirementDate: '2026-09-30', capacity: 100 }
      { name: 'gpt-5.2', sku: 'GlobalStandard', modelFormat: 'OpenAI', modelVersion: '2025-12-11', retirementDate: '2027-02-05', capacity: 100 }
      { name: 'text-embedding-3-large', sku: 'GlobalStandard', modelFormat: 'OpenAI', modelVersion: '1', retirementDate: '2027-04-14', capacity: 100 }
    ]
    priority: 1
    weight: 100
  }
  {
    backendId: 'aif-citadel-flux'
    backendType: 'azure-flux'
    endpoint: 'https://aif-rmwzy2zdoizg2-0.services.ai.azure.com/'
    authType: 'managed-identity'
    supportedModels: [
      { name: 'FLUX.2-pro', modelFormat: 'BlackForestLabs', modelVersion: '1', modelPath: 'flux-2-pro' }
    ]
    priority: 1
    weight: 100
  }
  {
    backendId: 'aif-citadel-mai'
    backendType: 'azure-mai'
    endpoint: 'https://aif-rmwzy2zdoizg2-0.services.ai.azure.com/'
    authType: 'managed-identity'
    supportedModels: [
      { name: 'MAI-Image-2.5-Flash', modelFormat: 'MAI', modelVersion: '1' }
    ]
    priority: 1
    weight: 100
  }
]

param configureCircuitBreaker = true
